### ISSUE TITLE
Filter query for "or"

### ISSUE THREAD

**Issue by arm358** [kit-oz/drf-complex-filter#3]
my query looks like this:
`/api/?filters={"type":"or","data":[{"attribute":"price","operator":"=","value":"100"},{"attribute":"brand","operator":"=","value":"Generic"}]}`

but I receive a KeyError which is traced to getting the `sub_query` and `sub_annotation` values on line 64 in `utils.py`. When `filter_data` is passed into the function again, it does not include the `"type"` value (in this case, `"or"`) since it's only looping through the `"data": [{},{},...]` list in the query. This yields a KeyError on line 41 in `utils.py`.

Does the request query have the right syntax for the `or` operator?

**Comment by kit-oz** [comment]
Hi!
The correct version would be
```
{"type": "or", "data": [
  {"type": "operator", "data": {"attribute":"price","operator":"=","value":"100"}},
  {"type": "operator", "data": {"attribute":"brand","operator":"=","value":"Generic"}}
]}
```

Generally, each statement is an object with two keys - `type` and `data`, where `data` can take one of two values:
* object with `attribute`, `operator` and `value` keys when type is `operator`
* array of another statements when type is `and` or `or`
